### ISSUE TITLE
Blank Website

### ISSUE THREAD

**Issue by Gabriel780** [yagiziskirik/Kerbal-Telemetry#17]
Is there any reason why my server is a blank website? 
I installed Kerbal-Telemtry from Ckan, the icon in the toolbar is white and the website is blank.

**Comment by yagiziskirik** [comment]
Hi @Gabriel780,

I am sorry to hear that you are experiencing such problem.

You might have installed a version that I accidentally uploaded. Can you look at the GameData folder and verify that you have `Kerbal Telemetry` folder? In that folder, you should have the following files and folders:
<img width="321" alt="Screenshot 2022-06-21 at 22 39 38" src="https://user-images.githubusercontent.com/33431578/174884094-db737806-0284-4570-a345-8c9c2af76fb8.png">

After confirming the files, you might have to reload the page to see if any changes happened. You might probably say that it is correct by looking for if the toolbar icon is fixed.

**Comment by Gabriel780** [comment]
I use v2.3.0
![image](https://user-images.githubusercontent.com/76402742/174929422-40364f16-7953-4923-af23-884f5ccd3841.png)
It still doesn't work. 
![image](https://user-images.githubusercontent.com/76402742/174929473-211e1083-1a5e-4054-a86b-a2563d560b5e.png)
I got it to work using the CKAN dll and code section files, but it only works with one ship and then I couldn't do anything else, once the ship was lost the mod did not respond..

**Comment by stekodev** [comment]
Hi @Gabriel780 

you just need to rename the folder, currently yours is "Kerbal-Telemetry", but it needs to be "Kerbal Telemetry".

This is at least what the server is looking for regarding the source code:
![image](https://user-images.githubusercontent.com/102827625/175664005-82d76d70-6179-4ce3-b163-8c1632df8405.png)

I think the package is not correct, so CKAN extracts it right in the root of the GameData folder for me in this case.

Greetings,
steko

**Comment by Gabriel780** [comment]
Now it works, thanks for this amazing project.

**Comment by Gabriel780** [comment]
Now it works, thanks for this amazing project.

**Comment by yagiziskirik** [comment]
I couldn't respond in time, but @stekodev perfectly explained the situation! This will be fixed in the following updates to avoid confusion amongst the operating systems and unarchivers.

Also, thanks for using my mod! You guys help me get things much better!
