### ISSUE TITLE
A few minor problems.

### ISSUE THREAD

**Issue by Aebestach** [yagiziskirik/Kerbal-Telemetry#2]
hello, @yagiziskirik 
I just tried to modify your source code, so that the generated JSON file does not contain Chinese characters, the effect is still good and can be used normally.
But also found a new problem at the same time, China is no way to access "https://code.jquery.com/jquery-3.5.1.js" on this site, you can see whether the next version of the "/static/sources" placing a "jQuery. js" file, the appearance of some setting "wall“ country or region can also be used normally, some players have no VPN)

**Comment by yagiziskirik** [comment]
I can simply include jquery file locally. I will check it out in half an hour. Thank you!

**Comment by Aebestach** [comment]
Looking forward to the next version update.😊

**Comment by yagiziskirik** [comment]
I moved all the required CDN's to the local file system. It will take place in the next update! Thanks again!
