### ISSUE TITLE
When Reverting Flight Would Add More Toolbar Icon To The Toolbar

### ISSUE THREAD

**Issue by towermom9** [yagiziskirik/Kerbal-Telemetry#20]
**Describe the bug**
I think the title explains it self

**To Reproduce**
Steps to reproduce the behaviour:
1.Spawn in a craft
2.Crash
3.Revert to lunch

**Expected behaviour**
I think the title explains it self

**Screenshots**
![image](https://user-images.githubusercontent.com/70556779/180772063-e9f7f6c6-2326-4794-966f-df9b6b9899b6.png)

**Device Information (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Kerbal Telemetry Version: 2.3.0
 - KSP Version: 1.12.3
 - Python Version: standalone one

**Additional context**

**Comment by McClainJ** [comment]
This bug also occurs when reloading into a vessel from the tracking center.

**Comment by yagiziskirik** [comment]
Hi @McClainJ,

The bug has recently been reported several times, it is going to be fixed in the next update. Since I have a very tight schedule, I have little to no time to spend on this project.

As soon as a new update comes, I will let you know!

**Comment by towermom9** [comment]
ah i see sorry to bother you

**Comment by yagiziskirik** [comment]
No problem at all! I hope you will enjoy it in the next update!

**Comment by yagiziskirik** [comment]
Guys, I managed to fix this problem and it is now functioning very well. As soon as I fix #22 and add a couple of new features and test it, the new update is on the way! Thank you for your patience, you guys are the best!

**Comment by yagiziskirik** [comment]
[v2.4.0](https://github.com/yagiziskirik/Kerbal-Telemetry/releases/tag/v2.4.0) fixes the issue. Thanks for your patience!
