### ISSUE TITLE
Mod causes extreme lagging.

### ISSUE THREAD

**Issue by MicroPanda123** [yagiziskirik/Kerbal-Telemetry#22]
When installed mod correctly (aka installing and changing name of folder from Kerbal-Telemetry to Kerbal Telemetry), game started lagging during flights so that it's unplayable.

OS: Fedora Linux 36
Browser: Firefox
Kerbal telemetry Version: 2.3.0
KSP Version: 1.12.3.3173
Python Version: 3.10.6

I know for a fact it's caused by this mod because removing it fixed that issue. And also it's not when you actually launch server, it happens everytime I launch the game, it lags so much you can't even get to the point of launching it.

**Comment by MicroPanda123** [comment]
Ok after waiting couple of minutes it started to work normally. Still kinda sucks that had to wait couple of minutes for it to work.

**Comment by MicroPanda123** [comment]
Now caused lag when opening map.

**Comment by MicroPanda123** [comment]
Coming back from map also causes lag.

**Comment by yagiziskirik** [comment]
Hi @MicroPanda123,

I've seen the other issue you created and I am glad that one of the other issues solved the problem for you. I think the Linux version of the program may cause it. The mod shouldn't be running before the game's flight section, but I think I should test it to come up with a conclusion. It would take some time for me to create a Linux environment to try it. But I will let you know once it is done.

**Comment by MicroPanda123** [comment]
I think I phrased it wrongly, I meant it starts lagging right at the start of game's flight section (still before you can actually launch server from mod menu), not on launch of the game. Sorry for misunderstanding.

**Comment by lnchenxiyan** [comment]
I got the same issue on Windows here too. The KSP not responded in the begaining of the flight section, needs to wait at least 5 mins to get normal. And I map section, the KSP just keep not responding for ever.

**Comment by yagiziskirik** [comment]
@MicroPanda123, @lnchenxiyan what are your system specifications? And do you have other mods running as well? Maybe it is caused by other mods but I couldn't simulate the same behaviour both in Windows and Linux. If both of you have a similar problem, there should be a common ground that causing the problem. Your list of mods could help me out!

**Comment by MicroPanda123** [comment]
@yagiziskirik I've exported my mod list from ckan and I add it here.
[modlist.txt](https://github.com/yagiziskirik/Kerbal-Telemetry/files/9484992/modlist.txt)
And my specifications are:
AMD Ryzen 7 3750H
NVIDIA GeForce RTX 2060 Mobile
16 GB of ram.

**Comment by yagiziskirik** [comment]
Thanks, @MicroPanda123! I am downloading the mods now. As soon as my test is finished, I would let you know.

**Comment by lnchenxiyan** [comment]
> Yes you are right, I tested with KT mod only and the lag has gone. Must be caused by other mods. 

[Mod_List.txt](https://github.com/yagiziskirik/Kerbal-Telemetry/files/9488085/Mod_List.txt)


Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz   3.10 GHz
RAM	32.0 GB (31.8 GB usable)
GeForce RTX 2070

**Comment by yagiziskirik** [comment]
Alright guys, I can see the issue now. It happens on Mac as well. I am deleting the mods one by one the understand which is causing the problem.

Also, I have both of your `mod_list.txt` files. As far as I could programmatically extract, these are the common mods that you have:
```
B9PartSwitch
ClickThroughBlocker
CommunityResourcePack
CustomPreLaunchChecks
DynamicBatteryStorage
Harmony2
JanitorsCloset
KerbalEngineerRedux
KerbalKonstructs
KSPCommunityFixes
MechJeb2
ModuleManager
NearFutureElectrical
NearFutureElectrical-Core
NearFuturePropulsion
NearFutureSolar
NearFutureSolar-Core
SpaceTuxLibrary
ToolbarController
ZeroMiniAVC
```

So it should be one of them that causes the problem. I will let you know which one, and possibly solve the issue.

**Comment by 8-monkey** [comment]
It's Janitor's Closet, and I guess the issue is caused by #22. Janitor's Closet allows you to hide UI buttons, and this mod seems to add the button in an unusual way (as it does it for every launch). Uninstalling either of the two mods solved the problem for me, having both causes extreme lag and a memory leak.

**Comment by yagiziskirik** [comment]
I also discovered that it is caused by Janitor's Closet, as @8-monkey stated amazingly. I didn't know how to make the buttons, and as a result, this happened. I will try to standardise everything in the next update anyway, but this would help me immensely.

I am so sorry for the delay in both replies and the solutions. I am trying to graduate and have so little time to spend on my hobbies.

**Comment by 8-monkey** [comment]
No worries, life always has priority. Maybe you can reach out to linuxgurugamer (maintainer of Janitor's Closet and a bazillion other mods) or some other experienced mod maker for some hints about implementing the buttons.

**Comment by MicroPanda123** [comment]
Yeah! It's totally fine.

**Comment by yagiziskirik** [comment]
Guys, I fixed it! Apparently I "accidentally" used an 8k resolution for the toolbar icon. After trying countless solutions, I finally fixed the problem. I am currently planning to integrate a few extras, after that, I am planning to release the new version. I appreciate your help and patience, thank you!

**Comment by MicroPanda123** [comment]
Yay!
Can't wait for release.

**Comment by lnchenxiyan** [comment]
thumbs up

**Comment by yagiziskirik** [comment]
[v2.4.0](https://github.com/yagiziskirik/Kerbal-Telemetry/releases/tag/v2.4.0) fixes the issue. Thanks for your patience!
