### ISSUE TITLE
White empty page

### ISSUE THREAD

**Issue by lnchenxiyan** [yagiziskirik/Kerbal-Telemetry#23]
yagiziskirik, firstly thank you for making this wonderful mod, couldn’t wait to try it.

However, when I run it, the localhost:8000 is reachable but only show white empty page. Do you know where could went wrong? My KSP is up to date, and I downloaded the Kerbal Telemetry on CKAN.

Thanks

**Comment by lnchenxiyan** [comment]
yagiziskirik, I found the issue. The CKAN extracted the file directly into GameData folder, not Kerbal Telemetry. I created the folder and moved all files in it then everything worked.

**Comment by yagiziskirik** [comment]
Hi @lnchenxiyan,

First of all, thanks for using the mod. Unfortunately, CKAN tends to do this on some machines but not all. I couldn't find a proper solution to the problem yet, I hope in the next update, it will be fixed. Also if you need any further assistance, please don't hesitate to ask. You can also check the similar issue of #17 if the problem occurs one more time. Have an amazing day!
