### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by theHubert** [yagiziskirik/Kerbal-Telemetry#24]
**Describe the bug**
I can install the mod normally. The corresponding tile on the right side is blank but opens a small window to start the server. When I open "http://localhost:8000/" only a white page appears.

**Screenshots**
<img width="35" alt="bug" src="https://user-images.githubusercontent.com/48258714/193142536-dfb1e3a1-342f-49e9-8a37-623cb15e2b66.png">

**Device Information (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and Brave
 - Kerbal Telemetry Version: v2.3
 - KSP Version: 1.12.3
 - Mod Manager: ckan

**Comment by Squeak-y** [comment]
Same as above,

Also tried in Edge & IE just in case and same issue.
Also tried with IP & Localhost on both the host and a mobile device and same issue.

**Comment by Ariyn** [comment]
I had same problem and fix it.

Check your mod folder installed correctly.

My original path looks like this.
`Kerbal Space Program/GameData/Kerbal+Telemetry/Kerbal Telemetry`

Mod's path should be `Kerbal Space Program/GameData/Kerbal Telemetry`
It's space between "Kerbal" and "Telemetry" not plus sign.

Check also "Kerbal Telemetry" folder contains "WebServer", "Texture", "Kerbal Telemetry.dll".

**Comment by theHubert** [comment]
Thanks, that was the issue.
ckan only put the .dll file in the folder.
To fix it I downloaded the mod from the website. I put all files, except the .dll file, in a "Kerbal Telemetry" folder. Then just add these two to the Game Data folder.

**Comment by yagiziskirik** [comment]
Hi guys!

The solution is as suggested by @Ariyn. I am currently back on the development since my workload decreased a bit, and I will be removing the spaces from the names. And I am having an issue with CKAN as well. I am (hopefully) fixing all the errors you guys mentioned. Thank you so much for the help!
