### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by genen** [yagiziskirik/Kerbal-Telemetry#3]
So before I take the time to install this, I don't see in the documentation if I need to install the same thing on 2 computers where one works as server the other as client. Or are there 2 different programs to install to do that? Or is it a web browser GUI so only installed on the Kerbal machine and any browser can be used as client? Just in general more docs or wiki would be appreciated since you warn that this is a 'Heavy utilization' python program.

Thanks!

**Comment by yagiziskirik** [comment]
Hello @genen, you are right. You only need to install it on the main computer which KSP is installed. So it is simply a web browser GUI as you said. After you install it on your computer, you can access the web interface from that computer's local IP address. I'm working on the README file right now, it is open on the other tab. Thank you for letting me know.
